# These are supported funding model platforms

github: rsalmei
ko_fi: rsalmei
custom: ["https://www.buymeacoffee.com/rsalmei", "https://www.paypal.com/donate?business=6SWSHEB5ZNS5N&no_recurring=0&item_name=I%27m+the+author+of+alive-progress%2C+clearly+and+about-time.+Thank+you+for+appreciating+my+work%21&currency_code=USD"]
